config/routes.rb
SampleApp::Application.routes.draw do
  get "password_resets/new"
  resources :users do
    member do
      get :following, :followers
    end
  end  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets
  resources :activate_accounts
  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',	to: 'sessions#new',			via: 'get'
  match '/signout',	to: 'sessions#destroy',		via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/views/notifier/confirm_email.html.erb
<p><%= @user.name %>,</p>

<p>Thanks for signing up! You are just one step away from having an active account.</p>

<p><%= link_to "Activate Your Account",
			edit_activate_account_url(id: @user.id,
					token: @user.confirm_token) %></p>

app/views/notifier/confirm_email.text.erb
<%= @user.name %>,

Thanks for signing up! You are just one step away from having an active account.

To confirm your email address and activate your account, go to the address below:

<%= edit_activate_account_url(id: @user.id,
					token: @user.confirm_token) %>

app/views/notifier/follower_notification.html.erb
<p><%= @user.name %>,</p>

<p><%= @follower.name %> (<%= link_to "@#{@follower.username}", user_url(@follower) %>) is following you on Sample App.</p>

<p>You can <%= link_to "change your settings for notifications", edit_user_url(@user) %></p>

<p><%= link_to "Sign in to micropost something", root_url %></p>

<p>Regards,
<br>Sample App</p>

app/views/notifier/follower_notification.text.erb
<%= @user.name %>,

<%= @follower.name %> (@<%= @follower.username %>) is following you on Sample App.

You can change your settings for notifications: <%= edit_user_url(@user) %>

Sign in to micropost something: <%= root_url %>

Regards,
Sample App

app/views/notifier/password_reset.html.erb
<p><%= @user.name %>,</p>

<p><%= link_to "Click here to reset your password",
			edit_password_reset_url(@user.password_reset_token) %></p>

<p>If you did not request your password to be reset just ignore this email and your password will continue to stay the same.</p>

app/views/notifier/password_reset.text.erb
<%= @user.name %>,

To reset your password, click the URL below.

<%= edit_password_reset_url(@user.password_reset_token) %>

If you did not request your password to be reset just ignore this email and your password will continue to stay the same.